### ISSUE TITLE
Doctests fail in 9.2.2

### ISSUE THREAD

**Issue by locallycompact** [gspia/fcf-containers#7]
Hi, bumping the stack yaml to nightly-2022-05-25 and running stack test, get many errors like these:

```
src/Fcf/Data/Tree.hs:143: failure in expression `:kind! Eval (Flatten ('Node 1 '[ 'Node 2 '[ 'Node 3 '[ 'Node 4 '[]]], 'Node 5 '[ 'Node 6 '[]]]))'
expected: Eval (Flatten ('Node 1 '[ 'Node 2 '[ 'Node 3 '[ 'Node 4 '[]]], 'Node 5 '[ 'Node 6 '[]]])) :: [Nat]
          = '[1, 2, 3, 4, 5, 6]
 but got: Eval (Flatten ('Node 1 '[ 'Node 2 '[ 'Node 3 '[ 'Node 4 '[]]], 'Node 5 '[ 'Node 6 '[]]])) :: [TL.Natural]
                                                                                                        ^
          = '[1, 2, 3, 4, 5, 6]
```

**Comment by gspia** [comment]
I'll start looking into this.

**Comment by gspia** [comment]
@locallycompact Hi, I got the doctests working locally and after some pipeline mangling and updating them to use 9.0 and 9.2 ghc's, also these github pipelines give green light now. 
If you have time, would you mind getting the sources and checking if they work for you?
In any case, I'll prepare a next minor version publication soon(ish).

**Comment by gspia** [comment]
And now it is published at the hackage. I'll close this issue and hope that this works now. If not, could you please re-open.
